apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  MYSQL_PASSWORD: wordpress
  MYSQL_ROOT_PASSWORD: wordpress
  MYSQL_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpress
  WORDPRESS_DB_USER: wordpress