apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  MYSQL_PASSWORD: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_USER: d29yZHByZXNz